# Generated by Django 5.1.6 on 2025-02-21 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('purpose_of_travel', models.TextField()),
                ('travel_start_date', models.DateField()),
                ('travel_mode', models.CharField(choices=[('Flight', 'By Flight'), ('Train', 'By Train'), ('Bus', 'By Bus'), ('Car', 'By Car')], max_length=10)),
                ('ticket_booking_mode', models.CharField(choices=[('Self', 'Self'), ('Travel Desk', 'Travel Desk')], max_length=20)),
                ('travel_start_location', models.CharField(max_length=255)),
                ('travel_end_location', models.CharField(max_length=255)),
                ('is_round_trip', models.BooleanField(default=False)),
                ('return_travel_start_date', models.DateField(blank=True, null=True)),
                ('return_travel_mode', models.CharField(blank=True, choices=[('Flight', 'By Flight'), ('Train', 'By Train'), ('Bus', 'By Bus'), ('Car', 'By Car')], max_length=10, null=True)),
                ('return_ticket_booking_mode', models.CharField(blank=True, choices=[('Self', 'Self'), ('Travel Desk', 'Travel Desk')], max_length=20, null=True)),
                ('return_travel_start_location', models.CharField(blank=True, max_length=255, null=True)),
                ('return_travel_end_location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
