# Generated by Django 5.1.6 on 2025-02-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
