# Generated by Django 5.1.6 on 2025-02-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_trip_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='is_round_trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_ticket_booking_mode',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_travel_end_location',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_travel_mode',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_travel_start_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='return_travel_start_location',
        ),
    ]
