# Generated by Django 5.1.6 on 2025-03-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_remove_trip_is_round_trip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
