# Generated by Django 5.1.6 on 2025-03-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0006_app_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='points',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
