# Generated by Django 5.1.6 on 2025-03-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_usertask_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='points',
        ),
    ]
